<?php

namespace App\Support;

/**
 * API Documentation Constants.
 *
 * Provides standardized PHPDoc response examples and documentation constants
 * for use across all API controllers. These constants ensure consistency
 * in API documentation generated by Scramble.
 */
final class ApiDocumentation
{
    // =========================================================================
    // RATE LIMIT DESCRIPTIONS
    // =========================================================================

    public const RATE_LIMIT_DEFAULT = 'Rate limit: 60 requests per minute.';

    public const RATE_LIMIT_AUTH = 'Rate limit: 10 requests per minute.';

    public const RATE_LIMIT_ENROLLMENT = 'Rate limit: 5 requests per minute.';

    // =========================================================================
    // RATE LIMIT HEADERS (for PHPDoc @header annotations)
    // =========================================================================

    public const RATE_LIMIT_HEADERS = <<<'DOC'
Headers yang dikembalikan:
- `X-RateLimit-Limit`: Jumlah maksimum request yang diizinkan per periode
- `X-RateLimit-Remaining`: Jumlah request tersisa dalam periode saat ini
- `Retry-After`: (hanya pada 429) Waktu dalam detik sebelum dapat mencoba lagi
DOC;

    // =========================================================================
    // STANDARD ERROR RESPONSES (JSON strings for @response annotations)
    // =========================================================================

    public const ERROR_401 = '{"success":false,"message":"Token tidak valid atau tidak ada","data":null,"meta":null,"errors":null}';

    public const ERROR_403 = '{"success":false,"message":"Anda tidak memiliki akses untuk melakukan operasi ini","data":null,"meta":null,"errors":null}';

    public const ERROR_404_GENERIC = '{"success":false,"message":"Resource tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_422_GENERIC = '{"success":false,"message":"Data yang Anda kirim tidak valid. Periksa kembali isian Anda.","data":null,"meta":null,"errors":{"field":["Pesan error validasi"]}}';

    public const ERROR_429 = '{"success":false,"message":"Terlalu banyak permintaan. Silakan coba lagi dalam 60 detik.","data":null,"meta":{"retry_after":60},"errors":null}';

    public const ERROR_500 = '{"success":false,"message":"Terjadi kesalahan pada server","data":null,"meta":null,"errors":null}';

    // =========================================================================
    // RESOURCE-SPECIFIC 404 ERRORS
    // =========================================================================

    public const ERROR_404_USER = '{"success":false,"message":"Pengguna tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_COURSE = '{"success":false,"message":"Kursus tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_ANNOUNCEMENT = '{"success":false,"message":"Pengumuman tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_NEWS = '{"success":false,"message":"Berita tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_THREAD = '{"success":false,"message":"Thread diskusi tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_ASSIGNMENT = '{"success":false,"message":"Tugas tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_SUBMISSION = '{"success":false,"message":"Pengumpulan tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_ENROLLMENT = '{"success":false,"message":"Pendaftaran tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_NOTIFICATION = '{"success":false,"message":"Notifikasi tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_BADGE = '{"success":false,"message":"Badge tidak ditemukan","data":null,"meta":null,"errors":null}';

    public const ERROR_404_CATEGORY = '{"success":false,"message":"Kategori tidak ditemukan","data":null,"meta":null,"errors":null}';

    // =========================================================================
    // PAGINATION META EXAMPLE
    // =========================================================================

    public const PAGINATION_META = '"meta":{"pagination":{"current_page":1,"per_page":15,"total":75,"last_page":5,"from":1,"to":15,"has_next":true,"has_prev":false}}';

    // =========================================================================
    // AUTHORIZATION DESCRIPTIONS
    // =========================================================================

    public const AUTH_ADMIN_ONLY = 'Memerlukan role: Admin.';

    public const AUTH_ADMIN_INSTRUCTOR = 'Memerlukan role: Admin atau Instruktur.';

    public const AUTH_INSTRUCTOR_ONLY = 'Memerlukan role: Instruktur.';

    public const AUTH_ENROLLED_USER = 'User harus terdaftar di kursus untuk mengakses endpoint ini.';

    public const AUTH_OWNER_ONLY = 'Hanya pemilik resource yang dapat mengakses endpoint ini.';

    public const AUTH_OWNER_OR_ADMIN = 'Dapat diakses oleh pemilik resource atau Admin.';

    // =========================================================================
    // QUERY PARAMETER DESCRIPTIONS (Pagination & Sorting)
    // =========================================================================

    public const PARAM_PAGE = '@queryParam page integer Nomor halaman. Default: 1. Example: 1';

    public const PARAM_PER_PAGE = '@queryParam per_page integer Jumlah item per halaman. Default: 15. Example: 15';

    public const PARAM_SORT = '@queryParam sort string Field untuk sorting. Prefix dengan - untuk descending. Example: -created_at';

    public const PARAM_SEARCH = '@queryParam search string Kata kunci pencarian. Example: sertifikasi';

    // =========================================================================
    // FILTER PARAMETERS - Format: filter[nama_filter] dengan nilai yang valid
    // =========================================================================

    // Status filters (umum)
    public const FILTER_STATUS_CONTENT = '@queryParam filter[status] string Filter berdasarkan status. Nilai: draft, pending, published, archived. Example: published';

    public const FILTER_STATUS_USER = '@queryParam filter[status] string Filter berdasarkan status user. Nilai: active, inactive, suspended. Example: active';

    public const FILTER_STATUS_ENROLLMENT = '@queryParam filter[status] string Filter berdasarkan status pendaftaran. Nilai: pending, active, completed, cancelled. Example: active';

    public const FILTER_STATUS_ASSIGNMENT = '@queryParam filter[status] string Filter berdasarkan status tugas. Nilai: draft, published, closed. Example: published';

    public const FILTER_STATUS_SUBMISSION = '@queryParam filter[status] string Filter berdasarkan status pengumpulan. Nilai: pending, submitted, graded, returned. Example: submitted';

    // Course filters
    public const FILTER_COURSE_ID = '@queryParam filter[course_id] integer Filter berdasarkan ID kursus. Example: 1';

    public const FILTER_DIFFICULTY = '@queryParam filter[difficulty_level] string Filter berdasarkan tingkat kesulitan. Nilai: beginner, intermediate, advanced. Example: beginner';

    public const FILTER_ENROLLMENT_TYPE = '@queryParam filter[enrollment_type] string Filter berdasarkan tipe pendaftaran. Nilai: open, key_required, approval_required. Example: open';

    // Announcement filters
    public const FILTER_PRIORITY = '@queryParam filter[priority] string Filter berdasarkan prioritas. Nilai: low, normal, high, urgent. Example: high';

    public const FILTER_TARGET_TYPE = '@queryParam filter[target_type] string Filter berdasarkan target. Nilai: all, course, role. Example: all';

    public const FILTER_UNREAD = '@queryParam filter[unread] boolean Filter hanya pengumuman yang belum dibaca. Nilai: true, false. Example: true';

    // News filters
    public const FILTER_IS_FEATURED = '@queryParam filter[featured] boolean Filter berita unggulan. Nilai: true, false. Example: true';

    public const FILTER_CATEGORY_ID = '@queryParam filter[category_id] integer Filter berdasarkan ID kategori. Example: 5';

    // Forum filters
    public const FILTER_IS_PINNED = '@queryParam filter[is_pinned] boolean Filter thread yang di-pin. Nilai: true, false. Example: true';

    public const FILTER_IS_LOCKED = '@queryParam filter[is_locked] boolean Filter thread yang dikunci. Nilai: true, false. Example: false';

    // User filters
    public const FILTER_ROLE = '@queryParam filter[role] string Filter berdasarkan role. Nilai: Admin, Instructor, Student. Example: Student';

    public const FILTER_EMAIL_VERIFIED = '@queryParam filter[email_verified] boolean Filter user yang sudah verifikasi email. Nilai: true, false. Example: true';

    // Date range filters
    public const FILTER_DATE_FROM = '@queryParam filter[date_from] string Filter dari tanggal (format: Y-m-d). Example: 2025-01-01';

    public const FILTER_DATE_TO = '@queryParam filter[date_to] string Filter sampai tanggal (format: Y-m-d). Example: 2025-12-31';

    // Notification filters
    public const FILTER_TYPE = '@queryParam filter[type] string Filter berdasarkan tipe notifikasi. Nilai: course_announcement, assignment_due, grade_released, forum_reply. Example: course_announcement';

    public const FILTER_READ = '@queryParam filter[read] boolean Filter notifikasi yang sudah/belum dibaca. Nilai: true, false. Example: false';

    // Gamification filters
    public const FILTER_BADGE_TYPE = '@queryParam filter[type] string Filter berdasarkan tipe badge. Nilai: achievement, milestone, special. Example: achievement';

    public const FILTER_LEADERBOARD_PERIOD = '@queryParam filter[period] string Filter periode leaderboard. Nilai: daily, weekly, monthly, all_time. Example: weekly';

    // =========================================================================
    // REALISTIC EXAMPLE DATA
    // =========================================================================

    /**
     * Get realistic user example data.
     */
    public static function userExample(int $id = 1): array
    {
        return [
            'id' => $id,
            'name' => 'Ahmad Rizki Pratama',
            'email' => 'ahmad.rizki@example.com',
            'username' => 'ahmadrizki',
            'status' => 'active',
            'email_verified_at' => '2025-01-15T10:30:00.000000Z',
            'created_at' => '2025-01-01T08:00:00.000000Z',
            'updated_at' => '2025-01-15T10:30:00.000000Z',
            'roles' => ['Student'],
        ];
    }

    /**
     * Get realistic course example data.
     */
    public static function courseExample(int $id = 1): array
    {
        return [
            'id' => $id,
            'title' => 'Skema Kompetensi Junior Web Developer',
            'slug' => 'skema-kompetensi-junior-web-developer',
            'description' => 'Skema sertifikasi untuk pengembang web tingkat junior yang mencakup HTML, CSS, JavaScript, dan dasar-dasar backend.',
            'status' => 'published',
            'enrollment_type' => 'open',
            'difficulty_level' => 'beginner',
            'created_at' => '2025-01-01T08:00:00.000000Z',
            'updated_at' => '2025-01-10T14:00:00.000000Z',
        ];
    }

    /**
     * Get realistic announcement example data.
     */
    public static function announcementExample(int $id = 1): array
    {
        return [
            'id' => $id,
            'title' => 'Jadwal Ujian Sertifikasi Batch Januari 2025',
            'content' => 'Kepada seluruh peserta sertifikasi, dengan ini kami informasikan bahwa ujian sertifikasi batch Januari 2025 akan dilaksanakan pada tanggal 25-27 Januari 2025.',
            'priority' => 'high',
            'target_type' => 'all',
            'status' => 'published',
            'published_at' => '2025-01-10T09:00:00.000000Z',
            'created_at' => '2025-01-10T08:00:00.000000Z',
            'updated_at' => '2025-01-10T09:00:00.000000Z',
        ];
    }

    /**
     * Get realistic news example data.
     */
    public static function newsExample(int $id = 1): array
    {
        return [
            'id' => $id,
            'title' => 'LSP Meluncurkan Program Sertifikasi Cloud Computing',
            'slug' => 'lsp-meluncurkan-program-sertifikasi-cloud-computing',
            'excerpt' => 'Dalam rangka memenuhi kebutuhan industri akan tenaga kerja terampil di bidang cloud computing, LSP resmi meluncurkan program sertifikasi baru.',
            'is_featured' => true,
            'views_count' => 1250,
            'status' => 'published',
            'published_at' => '2025-01-08T14:00:00.000000Z',
            'created_at' => '2025-01-08T10:00:00.000000Z',
            'updated_at' => '2025-01-08T14:00:00.000000Z',
        ];
    }

    /**
     * Get realistic enrollment example data.
     */
    public static function enrollmentExample(int $id = 1): array
    {
        return [
            'id' => $id,
            'user_id' => 1,
            'course_id' => 1,
            'status' => 'active',
            'enrolled_at' => '2025-01-15T10:00:00.000000Z',
            'completed_at' => null,
            'progress_percentage' => 35,
            'created_at' => '2025-01-15T10:00:00.000000Z',
            'updated_at' => '2025-01-20T14:30:00.000000Z',
        ];
    }

    /**
     * Get realistic notification example data.
     */
    public static function notificationExample(string $id = '550e8400-e29b-41d4-a716-446655440000'): array
    {
        return [
            'id' => $id,
            'type' => 'course_announcement',
            'title' => 'Pengumuman Baru di Kursus Anda',
            'message' => 'Ada pengumuman baru di kursus Skema Kompetensi Junior Web Developer',
            'read_at' => null,
            'created_at' => '2025-01-20T10:00:00.000000Z',
        ];
    }
}
